version: '3'

services:
  django:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    working_dir: /app/online_store


  react:
    build:
      context: online_store/frontend
    volumes:
      - frontend:/app
    ports:
      - "3000:3000"

volumes:
  frontend:


