version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
      # command: cd online_store && python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - react

  react:
    build:
      context: online_store/frontend
      dockerfile: Dockerfile
    command: sh -c "npm start"
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"


