# Generated by Django 4.2.7 on 2023-11-08 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
