# Generated by Django 4.2.7 on 2024-01-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_app', '0004_delete_category_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.TextField()),
            ],
            options={
                'db_table': 'Category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Like',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField()),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_price', models.IntegerField()),
                ('product_image', models.TextField()),
                ('product_comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_login', models.TextField()),
                ('seller_password', models.TextField()),
                ('seller_telephone', models.TextField(blank=True, null=True)),
                ('seller_name', models.TextField(blank=True, null=True)),
                ('seller_vk', models.TextField(blank=True, null=True)),
                ('seller_telegram', models.TextField(blank=True, null=True)),
                ('seller_insta', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Seller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.TextField()),
            ],
            options={
                'db_table': 'Status',
                'managed': False,
            },
        ),
    ]
